// Release gate for dsh-agency-agents-ll. Run with: pnpm verify
import { existsSync } from 'node:fs'
import { access, readFile, readdir, stat } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

let failures = 0
let warnings = 0

function check(label, condition, detail = '') {
  if (condition) {
    console.log(`通过：${label}`)
    return
  }
  failures += 1
  console.error(`失败：${label}${detail === '' ? '' : `（${detail}）`}`)
}

/**
 * Something that must not pass silently but is not a release failure. Kept out of
 * `failures` on purpose: a warning tells the truth about the local state without
 * turning `pnpm verify` into a command that requires a build first.
 */
function warn(label, detail = '') {
  warnings += 1
  console.warn(`提示：${label}${detail === '' ? '' : `（${detail}）`}`)
}

/**
 * Newest modification time anywhere under a directory, ignoring entries in `skip`
 * (absolute paths).
 * @param dir - directory to walk.
 * @param skip - absolute paths to ignore.
 * @returns the newest mtimeMs found, or 0 for an empty tree.
 */
async function newestMtime(dir, skip = new Set()) {
  let newest = 0
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (skip.has(full)) continue
    newest = Math.max(newest, entry.isDirectory() ? await newestMtime(full, skip) : (await stat(full)).mtimeMs)
  }
  return newest
}

const packageUrl = new URL('../package.json', import.meta.url)
const packageJson = JSON.parse(await readFile(packageUrl, 'utf8'))

check('包名与仓库一致', packageJson.name === 'dsh-agency-agents-ll', packageJson.name)
check('许可证为 Apache-2.0', packageJson.license === 'Apache-2.0')
check('声明 dsh.bundle.patch', packageJson.dsh?.bundle?.patch === './cordis.patch.yml')
check(
  '声明客户端半边',
  packageJson.dsh?.client?.platform === 'web' && Array.isArray(packageJson.dsh?.client?.inject),
)
// `dsh.client.inject` names the client modules that must be mounted before this
// one, so listing a module the host does not ship would leave the browser half
// permanently inactive. A package needed only for a type merge (an erased
// `import type {}`) belongs in devDependencies and must NOT be listed here.
const injected = packageJson.dsh?.client?.inject ?? []
const notPeer = injected.filter((name) => packageJson.peerDependencies?.[name] === undefined)
check(
  'dsh.client.inject 的每一项都声明为 peerDependency',
  injected.length > 0 && notPeer.length === 0,
  notPeer.join(', '),
)
check('发布文件齐全', ['lib', 'assets', 'cordis.patch.yml', 'README.md', 'NOTICE', 'LICENSE']
  .every((entry) => packageJson.files?.includes(entry)))
check('导出 Host 与客户端入口', packageJson.exports?.['.'] !== undefined && packageJson.exports?.['./client'] !== undefined)
// 0.1.7 keys the browser module table by package and refuses two active Loader
// rows resolving to the same one, so the Remote service is mounted by the Host
// half instead of shipping a second mountable entry.
check('不导出可单独挂载的 Remote 行', packageJson.exports?.['./remote'] === undefined)

for (const file of ['../lib/index.js', '../lib/client.js', '../cordis.patch.yml', '../LICENSE', '../NOTICE']) {
  try {
    await access(new URL(file, import.meta.url))
    check(`发布文件存在：${file.slice(3)}`, true)
  } catch {
    check(`发布文件存在：${file.slice(3)}`, false)
  }
}

// `lib/` is a gitignored build product, and every check below reads it rather
// than `src/`. That is the right target — it is what gets published, and
// `prepublishOnly` builds first — but it also means a local `pnpm verify` can
// describe a build that no longer matches the sources. Rebuilding here would turn
// the release gate into a build command, so the gap is reported instead.
try {
  const sourceDir = fileURLToPath(new URL('../src', import.meta.url))
  // `src/client/avatars.ts` is generated by `pnpm avatars:inline`, which
  // `pnpm verify` runs immediately before this script: its mtime is always "now",
  // so counting it would report a stale build on every single run.
  const generated = new Set([join(sourceDir, 'client', 'avatars.ts')])
  const sourceNewest = await newestMtime(sourceDir, generated)
  const builtNewest = await newestMtime(fileURLToPath(new URL('../lib', import.meta.url)))
  if (sourceNewest > builtNewest) {
    warn(
      'lib/ 比 src/ 旧，下面的检查描述的是 lib/ 而不是当前源码',
      `src 最新 ${new Date(sourceNewest).toISOString()}，lib 最新 ${new Date(builtNewest).toISOString()}；跑一次 pnpm build 再验证`,
    )
  } else {
    console.log('通过：lib/ 不早于 src/（下面的检查描述的就是当前源码）')
  }
} catch (error) {
  warn('无法比较 src/ 与 lib/ 的时间戳', error instanceof Error ? error.message : String(error))
}

const hostBundle = await readFile(new URL('../lib/index.js', import.meta.url), 'utf8')
const clientBundle = await readFile(new URL('../lib/client.js', import.meta.url), 'utf8')
check(
  '客户端产物带 ModuleLoader 工厂包装',
  clientBundle.includes('window.__ModuleLoader__.load(') && clientBundle.includes('dsh-agency-agents-ll'),
)
check('客户端产物不引用 Node url 模块', !clientBundle.includes('require("url")') && !clientBundle.includes("require('url')"))
// The platform-frozen table must stay external, otherwise the browser gets a
// second React/cordis instance instead of the host's. This is the web shell's
// `staticModules` seed table verbatim: a name the shell does not seed would miss
// the module table at require time, and a seeded name left out here would be
// inlined as a duplicate copy.
const PLATFORM_MODULES = [
  'react', 'react/jsx-runtime', 'react-dom', 'react-dom/client', '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store', '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives', '@deepseek-ai/dsh-client-ui-dockkit',
]
const bundleRequires = [...clientBundle.matchAll(/require\((["'])([^"']+)\1\)/g)].map((match) => match[2])
check(
  '客户端产物把平台冻结模块保持为 external',
  bundleRequires.every((id) => PLATFORM_MODULES.includes(id)),
  [...new Set(bundleRequires)].join(', '),
)
check(
  '客户端产物外部引用 react 而不是内联它',
  bundleRequires.includes('react') && !clientBundle.includes('__SECRET_INTERNALS'),
)
check(
  '客户端产物不引用 Node 内置模块',
  !bundleRequires.some((id) => id.startsWith('node:')),
  [...new Set(bundleRequires.filter((id) => id.startsWith('node:')))].join(', '),
)

const patch = await readFile(new URL('../cordis.patch.yml', import.meta.url), 'utf8')
check('Cordis patch 挂载当前包名', patch.includes(`name: ${packageJson.name}`))
// One row per package, and it is the only row: two active rows for the same
// package make the browser module registry reject the package outright, which
// costs the whole browser half rather than one of the two rows.
const patchRows = [...patch.matchAll(/^\s*name:\s*(\S+)\s*$/gmu)].map((match) => match[1])
check(
  'Cordis patch 只挂载一行且是本包',
  patchRows.length === 1 && patchRows[0] === packageJson.name,
  patchRows.join(', '),
)

const plugin = await import(new URL('../lib/index.js', import.meta.url).href)
check('编译入口导出 DSH 插件约定', ['name', 'Config', 'apply'].every((key) => key in plugin))
check('Host 半边自己挂载 Remote 服务', /ctx\.plugin\(\s*AgencyAgentsRemote\s*\)/u.test(hostBundle))

// 0.1.7 turned the strict codec from `schema` into a `create()` factory and
// validates it by that field; a codec without one is rejected while the gateway
// is registering the invocation, which takes every endpoint down with it.
const descriptors = plugin.AGENCY_AGENTS_DESCRIPTORS
check('编译产物导出两端共用的描述符表', Array.isArray(descriptors) && descriptors.length === 8, String(descriptors?.length))
check(
  '每个 strict codec 都带 create() 工厂',
  Array.isArray(descriptors) && descriptors.every((descriptor) => (
    typeof descriptor.result?.create === 'function'
    && descriptor.parameters.every((parameter) => typeof parameter.codec?.create === 'function')
  )),
)

const { resolvePromptLocale, coercePromptLocale } = await import(new URL('../lib/contract.js', import.meta.url).href)
check('auto 跟随宿主语言', resolvePromptLocale('auto', 'en') === 'en' && resolvePromptLocale('auto', 'zh') === 'zh')
check('显式偏好覆盖宿主语言', resolvePromptLocale('zh', 'en') === 'zh' && resolvePromptLocale('en', 'zh') === 'en')
check('未知取值回退默认', coercePromptLocale('fr') === 'en' && coercePromptLocale(undefined) === 'en')

// Division display names have exactly one home: src/names.ts. The sync glossary
// repeats them for translators, so a drift between the two is a gate failure
// rather than something a reviewer has to notice.
const { ZH_DIVISION, EN_DIVISION, DIVISIONS } = await import(new URL('../lib/names.js', import.meta.url).href)
const glossary = JSON.parse(await readFile(new URL('../sync/glossary.json', import.meta.url), 'utf8'))
const glossaryDivisions = Object.entries(glossary.terms ?? {})
  .filter(([key]) => key.startsWith('division:'))
  .map(([key, value]) => [key.slice('division:'.length), value])
check('分区数量为 18', DIVISIONS.length === 18, String(DIVISIONS.length))
check(
  '中英分区显示名一一对应',
  DIVISIONS.every((division) => ZH_DIVISION[division] !== undefined && EN_DIVISION[division] !== undefined),
)
check(
  'sync 术语表的分区名与 src/names.ts 一致',
  glossaryDivisions.length === DIVISIONS.length
    && glossaryDivisions.every(([division, value]) => ZH_DIVISION[division] === value),
  glossaryDivisions.filter(([division, value]) => ZH_DIVISION[division] !== value).map(([division]) => division).join(', '),
)

// The avatar brief hands out one filename per expert, so it is only usable
// while it names exactly the current roster. Regenerate with `pnpm avatars`.
const { roster } = await import('./avatar-manifest.mjs')
const avatarBrief = await readFile(new URL('../docs/AVATARS.md', import.meta.url), 'utf8')
const slugs = roster().map((row) => row.slug)
const briefSlugs = [...avatarBrief.matchAll(/^\| `([a-z0-9-]+)` \|/gm)].map((match) => match[1])
check(
  `docs/AVATARS.md 逐条对应名册（${slugs.length} 个专家）`,
  briefSlugs.length === slugs.length && briefSlugs.every((slug, index) => slug === slugs[index]),
  `清单 ${briefSlugs.length} 条，名册 ${slugs.length} 条；先跑 pnpm avatars`,
)

// The generated client module is ignored by git and lives only where the
// avatar tree does, so these gates have to hold in both worlds. Regenerating in
// memory and comparing is what makes that one statement instead of two: with a
// tree present it proves the module matches, and with none it proves the module
// is the empty map that a clean checkout produces.
const { render: renderAvatars } = await import('./avatars-inline.mjs')
const inlined = await readFile(new URL('../src/client/avatars.ts', import.meta.url), 'utf8')
check('src/client/avatars.ts 与 assets/avatar 一致', inlined === renderAvatars(), '先跑 pnpm avatars:inline')
const inlinedSlugs = [...inlined.matchAll(/^ {2}'([a-z0-9-]+)': 'data:image\/svg\+xml,/gm)].map((match) => match[1])
const strayAvatars = inlinedSlugs.filter((slug) => !slugs.includes(slug))
check(
  `每张头像都对应名册里的专家（${inlinedSlugs.length} 张）`,
  strayAvatars.length === 0,
  strayAvatars.slice(0, 5).join(', '),
)
const expectedAvatars = existsSync(new URL('../assets/avatar', import.meta.url)) ? slugs.length : 0
check(
  `头像数量与本地素材树相符（${inlinedSlugs.length} / ${expectedAvatars}）`,
  inlinedSlugs.length === expectedAvatars,
  expectedAvatars === 0
    ? '本机没有 assets/avatar，生成的应当是空模块'
    : `${expectedAvatars - inlinedSlugs.length} 个专家没有头像，会回退 emoji`,
)

if (failures > 0) {
  console.error(`\n${failures} 项验证失败`)
  process.exit(1)
}

console.log(`\n全部发布验证通过${warnings === 0 ? '' : `（另有 ${warnings} 项提示，见上）`}`)
